services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    env_file:
      - .env
    volumes: 
      - ./app:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - novumquay-network

networks:
  novumquay-network:
    external: true
